const DB_NAME="hanziQuestDB",DB_VERSION=2,STORE="state";
const state={xp:0,coins:0,combo:0,words:[],lessons:[],selectedLessonIds:null,session:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2)}
function defaultSkills(){return {meaning:{m:0,e:0},pinyin:{m:0,e:0},recognition:{m:0,e:0},listening:{m:0,e:0},writing:{m:0,e:0}}}
function normalizeWord(w){return {...w,id:w.id||uid(),skills:{...defaultSkills(),...(w.skills||{})},lessonIds:Array.isArray(w.lessonIds)?w.lessonIds:[],dueAt:w.dueAt||Date.now()}}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function load(){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(STORE,"readonly"),q=t.objectStore(STORE).get("main");q.onsuccess=()=>{if(q.result){Object.assign(state,q.result);state.words=(state.words||[]).map(normalizeWord);state.lessons=Array.isArray(state.lessons)?state.lessons:[];state.selectedLessonIds=Array.isArray(state.selectedLessonIds)?state.selectedLessonIds:null}else{state.words=[];state.lessons=[];state.selectedLessonIds=null}res()};q.onerror=()=>rej(q.error)})}
async function save(){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).put(JSON.parse(JSON.stringify(state)),"main");t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function selectedLessonObjects(){return (state.selectedLessonIds===null?[]:state.selectedLessonIds.map(id=>state.lessons.find(l=>l.id===id)).filter(Boolean))}
function activeWords(){if(state.selectedLessonIds===null)return state.words;const ids=new Set(state.selectedLessonIds);return state.words.filter(w=>(w.lessonIds||[]).some(id=>ids.has(id)))}
function filterLabel(){if(state.selectedLessonIds===null)return "Все слова";const ls=selectedLessonObjects();return ls.length?ls.map(l=>l.name).join(" + "):"Все слова"}
function updateHeader(){const all=state.words.length,active=activeWords().length;$("#xp").textContent=state.xp;$("#coins").textContent=state.coins;$("#combo").textContent=state.combo;$("#librarySummary").textContent=all?`${all} слов в словаре`:`Словарь пуст.`;$("#filterHeader").textContent=filterLabel();$("#selectionTitle").textContent=filterLabel();$("#selectionSummary").textContent=`${active} слов доступно${state.selectedLessonIds!==null&&selectedLessonObjects().length>1?" · можно выбрать несколько уроков":""}`}
function go(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));if(id==='library')renderLibrary();if(id==='lessons')renderLessons();if(id==='quest')startQuest();if(id==='pinyin')startSingle('pinyin');if(id==='listen')startSingle('listening');if(id==='write')startWriting();if(id==='boss')startBoss();scrollTo(0,0)}
$$('[data-screen]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.screen)));
$("#quitGame").onclick=()=>go('home');$("#closeModal").onclick=()=>$("#modal").classList.add('hidden');$("#createLesson").onclick=()=>showCreateLessonModal();$("#startSelectedQuest").onclick=()=>go('quest');$("#startSelectedBoss").onclick=()=>go('boss');$("#refreshLibrary").onclick=()=>renderLibrary();
function showModal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove('hidden')}
function closeModal(){ $("#modal").classList.add('hidden') }
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function chinese(s){return (String(s).match(/[\u3400-\u9fff]/g)||[]).join('')}
function parseDelimited(line,sep){const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++}else quoted=!quoted}else if(c===sep&&!quoted){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out}
function parseLine(line){line=line.trim();if(!line)return null;
  if(line.includes('|')||line.includes('\t')||line.includes(';')){const sep=line.includes('|')?'|':line.includes('\t')?'\t':';';const a=parseDelimited(line,sep);if(a.length>=3&&chinese(a[0]))return {hanzi:chinese(a[0]),pinyin:a[1],meaning:a.slice(2).join(' ')}}
  const comma=line.match(/^([^,]+),([^,]+),(.+)$/);if(comma&&chinese(comma[1]))return {hanzi:chinese(comma[1]),pinyin:comma[2].trim(),meaning:comma[3].trim()};
  const m=line.match(/^([^\s|,;]+)\s+(.+?)\s+(.+)$/);if(!m)return null;const h=chinese(m[1]);if(!h)return null;const rest=(m[2]+' '+m[3]).trim(),tokens=rest.split(/\s+/);const re=/^[A-Za-züÜāáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜńňḿ]+$/;let end=0;while(end<tokens.length&&re.test(tokens[end]))end++;if(end===0)return null;return {hanzi:h,pinyin:tokens.slice(0,end).join(' '),meaning:tokens.slice(end).join(' ')}
}
function parseFile(text,name){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/),rows=[],bad=[];lines.forEach((l,i)=>{if(!l.trim())return;const x=parseLine(l);if(x)rows.push({...x,id:uid(),skills:defaultSkills(),dueAt:Date.now(),lessonIds:[]});else bad.push(i+1)});return {rows,bad,total:lines.filter(x=>x.trim()).length,name}}
function lessonSelectOptions(selected=''){return `<option value="">Без урока</option>`+state.lessons.map(l=>`<option value="${esc(l.id)}" ${selected===l.id?'selected':''}>${esc(l.name)} (${state.words.filter(w=>(w.lessonIds||[]).includes(l.id)).length})</option>`).join('')}
$("#importBtn").onclick=()=>$("#fileInput").click();
$("#fileInput").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const text=await f.text();const p=parseFile(text,f.name);let table=p.rows.slice(0,12).map(x=>`<tr><td>${esc(x.hanzi)}</td><td>${esc(x.pinyin)}</td><td>${esc(x.meaning)}</td></tr>`).join('');showModal(`<h2>Предпросмотр импорта</h2><p class="notice"><b>${p.rows.length}</b> строк распознано из ${p.total}. ${p.bad.length?`Не распознано: строки ${p.bad.join(', ')}.`:'Все непустые строки распознаны.'}</p><table class="preview-table"><tr><th>汉字</th><th>Pinyin</th><th>Перевод</th></tr>${table}</table><label class="field-label" for="importLesson">Добавить в урок</label><div class="row"><select id="importLesson" class="select-field">${lessonSelectOptions()}</select><button class="secondary" id="newLessonFromImport">＋ Урок</button></div><p class="meta">Файл: ${esc(f.name)}. Слова ещё не добавлены.</p><button class="primary" id="confirmImport" style="width:100%;margin-top:12px">Добавить ${p.rows.length} слов</button>`);
  $("#newLessonFromImport").onclick=()=>{const name=prompt('Название нового урока:','Урок '+(state.lessons.length+1));if(!name?.trim())return;const id=uid();state.lessons.push({id,name:name.trim()});$("#importLesson").insertAdjacentHTML('beforeend',`<option value="${esc(id)}">${esc(name.trim())} (0)</option>`);$("#importLesson").value=id};
  $("#confirmImport").onclick=async()=>{const lessonId=$("#importLesson").value||null;const map=new Map(state.words.map(w=>[w.hanzi+'|'+w.pinyin,w]));p.rows.forEach(w=>{const k=w.hanzi+'|'+w.pinyin;if(map.has(k)){const ex=map.get(k);if(lessonId&&!ex.lessonIds.includes(lessonId))ex.lessonIds.push(lessonId)}else{if(lessonId)w.lessonIds=[lessonId];map.set(k,w)}});const before=state.words.length;state.words=[...map.values()];const added=state.words.length-before;await save();updateHeader();closeModal();e.target.value='';renderLibrary();alert(`Добавлено новых слов: ${added}${lessonId?' · урок назначен':''}`)}
};

function showCreateLessonModal(){showModal(`<h2>Новый урок</h2><p class="notice">Назови блок урока, например «Урок 1 — Покупки».</p><label class="field-label" for="newLessonName">Название</label><input id="newLessonName" class="text-field" value="Урок ${state.lessons.length+1}" autofocus><button class="primary" id="saveLesson" style="width:100%;margin-top:12px">Создать урок</button>`);$("#saveLesson").onclick=async()=>{const name=$("#newLessonName").value.trim();if(!name)return;state.lessons.push({id:uid(),name});await save();closeModal();renderLessons();updateHeader()}}
function renderLessons(){const box=$("#lessonSelection");if(!state.words.length){box.innerHTML=`<div class="lesson-empty"><h3>Пока нет слов</h3><p>Сначала импортируй TXT/CSV. Перед добавлением можно выбрать урок.</p><button class="primary" onclick="document.getElementById('modal').classList.add('hidden');go('home')">На главную</button></div>`;return}
  const allSelected=state.selectedLessonIds===null;let html=`<button class="lesson-row ${allSelected?'selected':''}" data-lesson-all="1"><div class="lesson-main"><div class="lesson-check">${allSelected?'✓':''}</div><div><div class="lesson-name">Все слова</div><div class="lesson-count">${state.words.length} слов · общий словарь</div></div></div><div>›</div></button>`;
  if(state.lessons.length){html+=state.lessons.map(l=>{const selected=!allSelected&&state.selectedLessonIds.includes(l.id);const count=state.words.filter(w=>(w.lessonIds||[]).includes(l.id)).length;return `<div class="lesson-row ${selected?'selected':''}"><button class="lesson-main" data-lesson-id="${esc(l.id)}" style="background:transparent;text-align:left;flex:1"><div class="lesson-check">${selected?'✓':''}</div><div><div class="lesson-name">${esc(l.name)}</div><div class="lesson-count">${count} ${count===1?'слово':'слов'}</div></div></button><button class="lesson-delete" data-delete-lesson="${esc(l.id)}" aria-label="Удалить урок">⋯</button></div>`}).join('')}else html+=`<div class="lesson-empty"><p>Уроков ещё нет. Создай первый через ＋.</p></div>`;
  box.innerHTML=html;$('[data-lesson-all]')?.addEventListener('click',()=>{state.selectedLessonIds=null;persistAndRenderLessons()});$$('[data-lesson-id]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.lessonId;let ids=state.selectedLessonIds===null?state.lessons.map(l=>l.id):[...state.selectedLessonIds];if(state.selectedLessonIds===null){state.selectedLessonIds=[id]}else{let ids=[...state.selectedLessonIds];if(ids.includes(id))ids=ids.filter(x=>x!==id);else ids.push(id);state.selectedLessonIds=ids.length?ids:null}persistAndRenderLessons()}));$$('[data-delete-lesson]').forEach(b=>b.addEventListener('click',async()=>{const id=b.dataset.deleteLesson;const l=state.lessons.find(x=>x.id===id);if(!l)return;showModal(`<h3>Удалить урок «${esc(l.name)}»?</h3><p class="notice">Слова не удалятся — только исчезнет их принадлежность к этому уроку.</p><button class="primary" id="confirmDelete" style="width:100%">Удалить урок</button>`);$("#confirmDelete").onclick=async()=>{state.lessons=state.lessons.filter(x=>x.id!==id);state.words.forEach(w=>w.lessonIds=(w.lessonIds||[]).filter(x=>x!==id));if(state.selectedLessonIds!==null){state.selectedLessonIds=state.selectedLessonIds.filter(x=>x!==id);if(!state.selectedLessonIds.length)state.selectedLessonIds=null}await save();closeModal();renderLessons();updateHeader()}}))
}
async function persistAndRenderLessons(){await save();renderLessons();updateHeader()}
function assignWordModal(word){showModal(`<h2>Уроки для ${esc(word.hanzi)}</h2><p class="meta">${esc(word.pinyin)} · ${esc(word.meaning)}</p><div class="lesson-check-grid">${state.lessons.length?state.lessons.map(l=>`<label class="check-option"><input type="checkbox" data-word-lesson="${esc(l.id)}" ${(word.lessonIds||[]).includes(l.id)?'checked':''}> <span>${esc(l.name)}</span></label>`).join(''):'<div class="notice">Создай уроки в разделе «Уроки».</div>'}</div><button class="primary" id="saveWordLessons" style="width:100%;margin-top:12px">Сохранить</button>`);$("#saveWordLessons").onclick=async()=>{word.lessonIds=$$('[data-word-lesson]:checked').map(x=>x.dataset.wordLesson);await save();closeModal();renderLibrary()}}

function dueWords(skill,pool){const now=Date.now();return pool.filter(w=>w.dueAt<=now).sort((a,b)=>weakness(b,skill)-weakness(a,skill))}
function weakness(w,skill){const s=w.skills?.[skill];return s?Math.max(0,1-s.m)+s.e*.15:1}
function chooseWord(skill,pool=activeWords()){let a=dueWords(skill,pool);if(!a.length)a=shuffle(pool);return a[0]}
function touch(w,skill,ok,quality=1){const s=w.skills[skill]||(w.skills[skill]={m:0,e:0});quality=Math.max(0,Math.min(1,quality));if(ok){s.m=Math.min(1,s.m+.22*quality);s.e=Math.max(0,s.e-(.35*quality));w.dueAt=Date.now()+Math.max(2*60*1000,Math.round((1+s.m*18)*60*1000));state.combo++;state.xp+=Math.max(4,Math.round(10*quality));state.coins+=Math.max(1,Math.round(2*quality))}else{s.m=Math.max(0,s.m-.12);s.e++;w.dueAt=Date.now()+60*1000;state.combo=0;state.xp=Math.max(0,state.xp-2)}save();updateHeader()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function options(correct,field,pool=activeWords()){const vals=[];for(const x of shuffle(pool)){if(x.id===correct.id)continue;const v=String(x[field]??'').trim();if(v&&!vals.includes(v)&&v!==String(correct[field]??'').trim())vals.push(v);if(vals.length>=3)break}return shuffle([String(correct[field]??''),...vals])}
function noWords(target){const pool=activeWords();if(!state.words.length){$(target).innerHTML=`<div class="empty"><h3>Сначала добавь слова</h3><p>На главной нажми «Импорт TXT / CSV». Слова попадут в игру только после твоего подтверждения.</p><button class="primary" onclick="go('home')">На главную</button></div>`;return true}if(!pool.length){$(target).innerHTML=`<div class="empty"><h3>В выбранных уроках пока нет слов</h3><p>Выбери другой набор или добавь слова в эти уроки.</p><button class="primary" onclick="go('lessons')">Настроить уроки</button></div>`;return true}return false}

function renderMeaning(target,word,skill,promptText,nextCallback,pool=activeWords()){const opts=options(word,'meaning',pool);$(target).innerHTML=`<div class="question-card"><div class="prompt">${esc(promptText)}</div><div class="hanzi">${esc(word.hanzi)}</div><div class="meta">${esc(word.pinyin)}</div><div class="answers">${opts.map(o=>`<button class="answer" data-v="${encodeURIComponent(o)}">${esc(o)}</button>`).join('')}</div><div id="feedback"></div></div>`;$$(`${target} .answer`).forEach(b=>b.onclick=()=>{const ok=decodeURIComponent(b.dataset.v)===word.meaning;$$(`${target} .answer`).forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');touch(word,skill,ok);showFeedback(target,ok,ok?'Правильно! +10 XP':`Пока нет. Правильный ответ: ${word.meaning}`,nextCallback)})}
function renderPinyin(target,word,skill,nextCallback,pool=activeWords()){const opts=options(word,'pinyin',pool);$(target).innerHTML=`<div class="question-card"><div class="prompt">Как читается это слово?</div><div class="hanzi">${esc(word.hanzi)}</div><div class="meta">${esc(word.meaning)}</div><div class="answers">${opts.map(o=>`<button class="answer" data-v="${encodeURIComponent(o)}">${esc(o)}</button>`).join('')}</div><div id="feedback"></div></div>`;$$(`${target} .answer`).forEach(b=>b.onclick=()=>{const ok=decodeURIComponent(b.dataset.v)===word.pinyin;$$(`${target} .answer`).forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');touch(word,skill,ok);showFeedback(target,ok,ok?'Правильно! +10 XP':`Правильный pinyin: ${word.pinyin}`,nextCallback)})}
function renderRecognition(target,word,skill,promptText,nextCallback,pool=activeWords()){const opts=shuffle([word,...shuffle(pool.filter(x=>x.id!==word.id)).slice(0,3)]);$(target).innerHTML=`<div class="question-card"><div class="prompt">${esc(promptText)}<br><b>${esc(word.meaning)}</b></div><div class="answers">${opts.map(o=>`<button class="answer" data-v="${esc(o.id)}"><span style="font-size:42px">${esc(o.hanzi)}</span></button>`).join('')}</div><div id="feedback"></div></div>`;$$(`${target} .answer`).forEach(b=>b.onclick=()=>{const ok=b.dataset.v===word.id;$$(`${target} .answer`).forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');touch(word,skill,ok);showFeedback(target,ok,ok?'Узнала правильно! +10 XP':`Правильный иероглиф: ${word.hanzi}`,nextCallback)})}
function showFeedback(target,ok,message,next){const fb=$(target+' #feedback');if(!fb)return;fb.innerHTML=`<div class="feedback ${ok?'good':'bad'}">${esc(message)}</div><button class="primary next" id="next">Дальше</button>`;$(target+' #next').onclick=next}

function voiceList(){return ('speechSynthesis' in window)?speechSynthesis.getVoices():[]}
function findChineseVoice(){const voices=voiceList();return voices.find(v=>/^zh-(CN|Hans)/i.test(v.lang))||voices.find(v=>/^zh/i.test(v.lang))||null}
function speechAvailable(){return 'speechSynthesis' in window&&'SpeechSynthesisUtterance' in window}
function speakChinese(text,rate=.8,statusTarget){if(!speechAvailable()){if(statusTarget)$(statusTarget).textContent='Аудио недоступно в этом браузере.';return false}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const voice=findChineseVoice();u.voice=voice||null;u.lang=voice?.lang||'zh-CN';u.rate=rate;u.pitch=1;u.volume=1;if(statusTarget)$(statusTarget).textContent=voice?`Голос: ${voice.name}`:'Китайский системный голос не найден — iPad попробует стандартный zh-CN.';u.onstart=()=>{if(statusTarget)$(statusTarget).textContent='🔊 Воспроизведение…'};u.onend=()=>{if(statusTarget)$(statusTarget).textContent='Можно послушать ещё раз.'};u.onerror=e=>{if(statusTarget)$(statusTarget).textContent=`Аудио не запустилось (${e.error||'ошибка'}). Проверь звук и китайский голос в настройках iPad.`};speechSynthesis.resume();speechSynthesis.speak(u);return true}
function audioVoiceHint(){const voices=voiceList();const zh=voices.filter(v=>/^zh/i.test(v.lang));return {hasAny:voices.length>0,hasChinese:zh.length>0,names:zh.slice(0,3).map(v=>v.name)}}
function renderListening(target,word,skill,nextCallback,pool=activeWords(),bossMode=false){const opts=options(word,'meaning',pool);const id='audioStatus';$(target).innerHTML=`<div class="question-card"><div class="prompt">${bossMode?'Boss: ':''}Сначала прослушай слово, затем выбери перевод.</div><div class="listen-controls"><button class="primary" id="playAudio">🔊 Слушать</button><button class="secondary" id="slowAudio">🐢 Медленно</button></div><div id="${id}" class="audio-status"></div><div class="notice voice-panel"><b>Что слушаем:</b> китайское произношение. Письменный ответ заранее не показываем.</div><div class="answers">${opts.map(o=>`<button class="answer" data-v="${encodeURIComponent(o)}">${esc(o)}</button>`).join('')}</div><div id="feedback"></div></div>`;
  const status='#'+id;$(target+' #playAudio').onclick=()=>speakChinese(word.hanzi,.8,status);$(target+' #slowAudio').onclick=()=>speakChinese(word.hanzi,.58,status);const v=audioVoiceHint();$(status).textContent=v.hasChinese?`Китайских голосов найдено: ${v.names.join(', ')}`:v.hasAny?'Голоса есть, но zh-CN не найден — попробуем системный китайский голос.':'Голосовой список iPad ещё загружается. Нажми «Слушать» ещё раз через секунду.';
  $$(`${target} .answer`).forEach(b=>b.onclick=()=>{const ok=decodeURIComponent(b.dataset.v)===word.meaning;$$(`${target} .answer`).forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');touch(word,skill,ok);showFeedback(target,ok,ok?'На слух узнала правильно! +10 XP':`Пока нет. Правильный перевод: ${word.meaning}`,nextCallback)})
}
if(speechAvailable())speechSynthesis.onvoiceschanged=()=>{};

let questIndex=0;
function startQuest(){if(noWords('#question'))return;questIndex=0;state.session={};nextQuest()}
function nextQuest(){questIndex++;$("#questProgress").textContent=`${questIndex} / 5`;if(questIndex>5){$("#question").innerHTML=`<div class="result card"><div class="big">🏁</div><h2>Quest завершён</h2><p>XP, монеты и навыки сохранены.</p><button class="primary" onclick="go('home')">Продолжить</button></div>`;return}const pool=activeWords();const skills=['meaning','pinyin','recognition','listening'],skill=skills[Math.floor(Math.random()*skills.length)],w=chooseWord(skill,pool);if(skill==='meaning')renderMeaning('#question',w,skill,'Что означает это слово?',nextQuest,pool);else if(skill==='pinyin')renderPinyin('#question',w,skill,nextQuest,pool);else if(skill==='recognition')renderRecognition('#question',w,skill,'Какой иероглиф соответствует переводу:',nextQuest,pool);else renderListening('#question',w,skill,nextQuest,pool,false)}
function startSingle(skill){const target=skill==='pinyin'?'#pinyinQuestion':skill==='listening'?'#listenQuestion':'#question';if(noWords(target))return;const pool=activeWords(),w=chooseWord(skill,pool);if(skill==='pinyin')renderPinyin(target,w,skill,()=>startSingle(skill),pool);else renderListening(target,w,skill,()=>startSingle(skill),pool,false)}

let writeWord,writeWriter,writeCharIndex=0,writeChars=[];
function writingCharacters(word){return [...word.hanzi].filter(ch=>/[\u3400-\u9fff]/.test(ch))}
function writingQuality(mistakes){return mistakes<=2?1:mistakes<=5?.72:.45}
function startWriting(){if(noWords('#writeQuestion'))return;writeWord=chooseWord('writing',activeWords());writeChars=writingCharacters(writeWord);writeCharIndex=0;renderWritingCharacter()}
function renderWritingCharacter(){if(!writeChars.length){startWriting();return}const ch=writeChars[writeCharIndex];$("#writeQuestion").innerHTML=`<div class="question-card write-wrap"><div class="prompt">Напиши иероглиф по пиньинь и переводу · ${writeCharIndex+1} / ${writeChars.length}</div><div class="meta"><b>${esc(writeWord.pinyin)}</b> · ${esc(writeWord.meaning)}</div><div id="hanziPad" class="hanzi-pad"></div><div class="tools"><button class="secondary" id="showHint">Показать подсказку</button><button class="secondary" id="restartWrite">Заново</button></div><div class="notice" style="margin-top:12px">Проверка терпима к естественной неровности рукописного ввода. Оцениваются форма, направление и порядок штрихов.</div><div id="writeFeedback"></div></div>`;
  if(!window.HanziWriter){$("#writeFeedback").innerHTML='<div class="feedback bad">Движок письма не загрузился. Нужен интернет при первом запуске.</div>';return}
  writeWriter=HanziWriter.create('hanziPad',ch,{width:Math.min(430,window.innerWidth-70),height:Math.min(430,window.innerWidth-70),padding:18,showCharacter:false,showOutline:false,renderer:'canvas',drawingWidth:7,showHintAfterMisses:4,highlightOnComplete:true});$("#showHint").onclick=()=>writeWriter.showOutline({duration:180});$("#restartWrite").onclick=()=>{writeWriter.cancelQuiz();renderWritingCharacter()};
  writeWriter.quiz({leniency:1.55,showHintAfterMisses:4,markStrokeCorrectAfterMisses:6,acceptBackwardsStrokes:false,onMistake:data=>{$('#writeFeedback').innerHTML=`<div class="feedback bad">Небольшая неточность — продолжай. Ошибок на этом штрихе: ${data.mistakesOnStroke}</div>`},onCorrectStroke:data=>{$('#writeFeedback').innerHTML=`<div class="feedback good">Штрих принят ✓ Осталось: ${data.strokesRemaining}</div>`},onComplete:data=>{const mistakes=data.totalMistakes||0;const quality=writingQuality(mistakes);const text=mistakes<=2?'Отлично!':mistakes<=5?'Хорошо — рукописный вариант принят.':'Принято, но иероглиф стоит повторить ещё раз.';touch(writeWord,'writing',true,quality);$('#writeFeedback').innerHTML=`<div class="feedback good">${text} +${Math.max(4,Math.round(10*quality))} XP</div><button class="primary next" id="nextWrite">${writeCharIndex+1<writeChars.length?'Следующий иероглиф':'Следующее слово'}</button>`;$('#nextWrite').onclick=()=>{writeCharIndex++;if(writeCharIndex<writeChars.length)renderWritingCharacter();else startWriting()}}})}

let boss;
function startBoss(){if(noWords('#bossQuestion'))return;const pool=activeWords();boss={i:0,score:0,items:shuffle(pool).slice(0,Math.min(10,pool.length)),results:[],pool};bossNext()}
function bossNext(){if(boss.i>=boss.items.length){bossFinish();return}const w=boss.items[boss.i],skills=['meaning','pinyin','recognition','listening','writing'],skill=skills[boss.i%skills.length];$("#bossProgress").textContent=`${boss.i+1} / ${boss.items.length}`;if(skill==='writing'){const chars=writingCharacters(w),ch=chars[0]||w.hanzi[0];$("#bossQuestion").innerHTML=`<div class="question-card write-wrap"><div class="prompt">Boss: напиши иероглиф по пиньинь и переводу</div><div class="meta"><b>${esc(w.pinyin)}</b> · ${esc(w.meaning)}</div><div id="bossPad" class="hanzi-pad"></div><div class="notice">Мягкая проверка формы и порядка штрихов.</div><div id="bossFb"></div></div>`;if(!window.HanziWriter){$("#bossFb").innerHTML='<div class="feedback bad">Движок письма не загрузился.</div>';return}const bw=HanziWriter.create('bossPad',ch,{width:Math.min(430,window.innerWidth-70),height:Math.min(430,window.innerWidth-70),padding:18,showCharacter:false,showOutline:false,renderer:'canvas',drawingWidth:7,showHintAfterMisses:4,highlightOnComplete:true});bw.quiz({leniency:1.55,showHintAfterMisses:4,markStrokeCorrectAfterMisses:6,onComplete:data=>{const mistakes=data.totalMistakes||0;const quality=writingQuality(mistakes);const ok=true;touch(w,'writing',ok,quality);boss.results.push({skill,ok,mistakes});boss.i++;$('#bossFb').innerHTML=`<div class="feedback good">Принято. Ошибок: ${mistakes}. Следующее задание…</div>`;setTimeout(bossNext,700)}})}else if(skill==='meaning'){renderMeaning('#bossQuestion',w,skill,'Boss: выбери перевод',()=>bossAdvance(skill,w),boss.pool)}else if(skill==='pinyin'){renderPinyin('#bossQuestion',w,skill,()=>bossAdvance(skill,w),boss.pool)}else if(skill==='recognition'){renderRecognition('#bossQuestion',w,skill,'Boss: какой иероглиф соответствует переводу:',()=>bossAdvance(skill,w),boss.pool)}else{renderListening('#bossQuestion',w,skill,()=>bossAdvance(skill,w),boss.pool,true)}}
function bossAdvance(skill,w){const ok=$('#bossQuestion .feedback')?.classList.contains('good')||false;boss.results.push({skill,ok});boss.i++;setTimeout(bossNext,650)}
function bossFinish(){const labels={meaning:'значение',pinyin:'pinyin',recognition:'узнавание иероглифа',listening:'аудирование',writing:'письмо'};const failed=boss.results.filter(x=>!x.ok).map(x=>x.skill);const weakByModel=Object.keys(labels).map(skill=>{const vals=boss.pool.map(w=>w.skills?.[skill]?.m||0);return {skill,avg:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,errors:boss.pool.reduce((a,w)=>a+(w.skills?.[skill]?.e||0),0)}}).filter(x=>x.avg<.65||x.errors>1).sort((a,b)=>a.avg-b.avg);const recommendations=[...new Set([...failed,...weakByModel.map(x=>x.skill)])].map(x=>labels[x]);const passed=boss.results.filter(x=>x.ok).length;$("#bossQuestion").innerHTML=`<div class="result card"><div class="big">👑</div><h2>Boss завершён</h2><p>Результат: <b>${passed} / ${boss.results.length}</b></p><div class="result-grid"><div class="result-stat">Выборка<b>${boss.pool.length} слов</b></div><div class="result-stat">Набор<b>${esc(filterLabel())}</b></div></div><div class="recommend"><b>Что повторить:</b><br>${recommendations.length?recommendations.join(', '):'Слабых зон по текущей модели знаний не обнаружено.'}<br><span class="small-note">Рекомендации учитывают не только ошибки Boss, но и накопленный прогресс по выбранным словам — даже если ответ на Boss был правильным.</span></div><button class="primary next" onclick="go('home')">Вернуться</button></div>`}

function renderLibrary(){const pool=state.words;if(!pool.length){$("#libraryList").innerHTML=`<div class="empty"><h3>Словарь пуст</h3><p>Импортируй TXT или CSV с главной.</p></div>`;return}$("#libraryList").innerHTML=pool.map(w=>{const vals=Object.entries(w.skills).map(([k,v])=>`<span class="skill">${k}: ${Math.round(v.m*100)}%</span>`).join('');const badges=(w.lessonIds||[]).map(id=>state.lessons.find(l=>l.id===id)?.name).filter(Boolean).map(n=>`<span class="lesson-badge">${esc(n)}</span>`).join('')||'<span class="lesson-badge">Без урока</span>';return `<div class="library-item"><div><span class="hanzi-small">${esc(w.hanzi)}</span><b>${esc(w.pinyin)}</b></div><div class="meta">${esc(w.meaning)}</div><div>${badges}</div><button class="link-button" data-edit-word="${esc(w.id)}">Изменить уроки</button><div>${vals}</div></div>`}).join('');$$('[data-edit-word]').forEach(b=>b.onclick=()=>{const w=state.words.find(x=>x.id===b.dataset.editWord);if(w)assignWordModal(w)})}
(async()=>{try{await load();updateHeader();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(speechAvailable())speechSynthesis.getVoices()}catch(e){console.error(e)}})();
